### ISSUE TITLE
Nodes missing

### ISSUE THREAD

**Issue by sepion02** [aria1th/ComfyUI-LogicUtils#2]
I correctly cloned it but nodes are missing.
Any missing step to install those custom nodes ?

**Comment by diodiogod** [comment]
I use your nodes a lot on my worflows and people have being complaining about StingListToCombo missing... I don't know why. Apparently they need to reinstall it.

**Comment by aria1th** [comment]
@diodiogod I think it could be because of missing dependencies, I'll fix it...
