### ISSUE TITLE
What's wrong with it?

### ISSUE THREAD

**Issue by Elminsst** [aria1th/ComfyUI-LogicUtils#7]
Warning: INPUT_TYPES and function arguments don't match in SaveImageCustomNode, input_types: ['self', 'images', 'filename_prefix', 'subfolder_dir'], function arguments: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'prompt', 'extra_pnginfo', 'self']
Warning: INPUT_TYPES and function arguments don't match in SaveImageWebpCustomNode, input_types: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'quality', 'lossless', 'compression', 'optimize', 'metadata_string'], function arguments: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'prompt', 'extra_pnginfo', 'quality', 'lossless', 'compression', 'optimize', 'metadata_string', 'self']
Warning: args in function arguments in ResizeImageNode, skipping argument validation
Warning: args in function arguments in ResizeImageResolution, skipping argument validation
Warning: args in function arguments in Base64DecodeNode, skipping argument validation
Warning: args in function arguments in InvertImageNode, skipping argument validation
Warning: args in function arguments in ResizeScaleImageNode, skipping argument validation
Warning: args in function arguments in ResizeShortestToNode, skipping argument validation
Warning: args in function arguments in ResizeLongestToNode, skipping argument validation
Warning: args in function arguments in ConvertGreyscaleNode, skipping argument validation
Warning: args in function arguments in RotateImageNode, skipping argument validation
Warning: args in function arguments in BrightnessNode, skipping argument validation
Warning: args in function arguments in ContrastNode, skipping argument validation
Warning: args in function arguments in SharpnessNode, skipping argument validation
Warning: args in function arguments in ColorNode, skipping argument validation
Warning: args in function arguments in ConvertRGBNode, skipping argument validation
Warning: args in function arguments in ThresholdNode, skipping argument validation
Warning: args in function arguments in SDWebuiAPINode, skipping argument validation
Warning: args in function arguments in SDWebuiAPIFallbackNode, skipping argument validation

How to fix the waining?

**Comment by huang6kun** [comment]
same here

**Comment by aria1th** [comment]
@Elminsst @huang6kun The warning is just for sanity check - it does not mean its actual critical error, I'll reduce the log info in next release!

**Comment by huang6kun** [comment]
> @Elminsst @huang6kun The warning is just for sanity check - it does not mean its actual critical error, I'll reduce the log info in next release!

Thanks
